#source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'PLMediaStreamingKitDemo' do
  pod 'PLMediaStreamingKit', '~> 3.0.3'
  pod 'Masonry'
  pod 'BlocksKit'

  pod 'SVProgressHUD'
  
end
