source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'PLMediaStreamingKitDemo' do
  pod 'PLMediaStreamingKit', '~> 3.0.8'
  pod 'Masonry'
  pod 'BlocksKit'

  pod 'SVProgressHUD'
  pod 'FURenderKit', '~> 8.7.0'
  
end
